from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[]
    operations=[
        migrations.CreateModel(name='Category',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=80,unique=True)),('slug',models.SlugField(unique=True)),('icon',models.CharField(default='✦',max_length=30))]),
        migrations.CreateModel(name='Product',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=180)),('slug',models.SlugField(unique=True)),('short_description',models.CharField(max_length=240)),('description',models.TextField(blank=True)),('price',models.DecimalField(decimal_places=2,max_digits=10)),('old_price',models.DecimalField(blank=True,decimal_places=2,max_digits=10,null=True)),('stock',models.PositiveIntegerField(default=10)),('image_url',models.URLField(blank=True)),('badge',models.CharField(blank=True,max_length=30)),('featured',models.BooleanField(default=False)),('active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('category',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='products',to='shop.category'))]),
        migrations.CreateModel(name='Order',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('full_name',models.CharField(max_length=120)),('phone',models.CharField(max_length=30)),('email',models.EmailField(blank=True,max_length=254)),('city',models.CharField(max_length=80)),('address',models.TextField()),('payment_method',models.CharField(choices=[('cod','Cash on Delivery'),('easypaisa','Easypaisa'),('jazzcash','JazzCash')],default='cod',max_length=20)),('status',models.CharField(choices=[('pending','Pending'),('confirmed','Confirmed'),('packed','Packed'),('shipped','Shipped'),('delivered','Delivered'),('cancelled','Cancelled')],default='pending',max_length=20)),('subtotal',models.DecimalField(decimal_places=2,max_digits=12)),('shipping',models.DecimalField(decimal_places=2,default=199,max_digits=10)),('total',models.DecimalField(decimal_places=2,max_digits=12)),('notes',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='orders',to='auth.user'))]),
        migrations.CreateModel(name='OrderItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('product_name',models.CharField(max_length=180)),('price',models.DecimalField(decimal_places=2,max_digits=10)),('quantity',models.PositiveIntegerField()),('order',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='shop.order')),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='shop.product'))]),
    ]
